import { CombinedCurrencyData } from '../screens/MarketScreen';

export const MOCK_CURRENCY_DATA: CombinedCurrencyData[] = [
  // Bitcoin
  {
    color: '#F78B1A',
    currencyGroup: 'BTC',
    currencySymbol: 'BTC',
    decimal_point: 8,
    listingDate: '2020-09-15T09:43:45Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg',
    name: 'Bitcoin',
    wallets: [
      {
        blockchain: 'Bitcoin',
        blockchainName: 'Bitcoin',
        currencyGroup: 'BTC',
        decimal_point: 8,
        explorer: 'https://explorer.bitcoin.com/btc/tx/',
        listingDate: '2020-09-15T09:43:45Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/Bitcoin.svg',
        tokenSymbol: 'BTC',
        tokenType: 'Bitcoin',
      },
    ],
    price: {
      day: '-2.45',
      latestPrice: '454604863',
      month: '17.47',
      pair: 'btc/idr',
      week: '-0.60',
      year: '47.04',
    },
  },
  // ETH
  {
    color: '#9011FE',
    currencyGroup: 'ETH',
    currencySymbol: 'ETH',
    decimal_point: 18,
    listingDate: '2020-09-15T09:43:46Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_ETH.svg',
    name: 'Ethereum',
    wallets: [
      {
        blockchain: 'Ethereum',
        blockchainName: 'Ethereum',
        currencyGroup: 'ETH',
        decimal_point: 18,
        explorer: 'https://etherscan.io/tx/',
        listingDate: '2020-09-15T09:43:46Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/ERC-20.svg',
        tokenSymbol: 'ETH',
        tokenType: 'ERC-20',
      },
    ],
    price: {
      day: '-2.65',
      latestPrice: '29063139',
      month: '11.81',
      pair: 'eth/idr',
      week: '3.15',
      year: '62.18',
    },
  },
  // Tether (USDT)
  {
    color: '#15A57C',
    currencyGroup: 'USDT',
    currencySymbol: 'USDT',
    decimal_point: 6,
    listingDate: '2020-09-15T09:43:47Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_USDT.svg',
    name: 'Tether',
    wallets: [
      {
        // Only get the first 1 of 6
        blockchain: 'Ethereum',
        blockchainName: 'Ethereum',
        currencyGroup: 'USDT',
        decimal_point: 6,
        explorer: 'https://etherscan.io/tx/',
        listingDate: '2020-09-15T09:43:47Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/ERC-20.svg',
        tokenSymbol: 'USDT',
        tokenType: 'ERC-20',
      },
    ],
    price: {
      day: '0.33',
      latestPrice: '14994',
      month: '0.66',
      pair: 'usdt/idr',
      week: '-0.83',
      year: '-0.21',
    },
  },
  // Binance (BNB)
  {
    color: '#FEBF11',
    currencyGroup: 'BNB',
    currencySymbol: 'BNB',
    decimal_point: 8,
    listingDate: '2020-09-15T09:43:48Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BNB.svg',
    name: 'Binance Coin',
    wallets: [
      // Only get the first 1 of 2
      {
        blockchain: 'Binance',
        blockchainName: 'BNB Beacon Chain',
        currencyGroup: 'BNB',
        decimal_point: 8,
        explorer: 'https://explorer.binance.org/tx/',
        listingDate: '2020-09-15T09:43:48Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/BEP-2.svg',
        tokenSymbol: 'BNB',
        tokenType: 'BEP-2',
      },
    ],
    price: {
      day: '-1.04',
      latestPrice: '3782511',
      month: '2.25',
      pair: 'bnb/idr',
      week: '5.45',
      year: '5.62',
    },
  },
  // Compound
  {
    color: '#00D395',
    currencyGroup: 'COMP',
    currencySymbol: 'COMP',
    decimal_point: 18,
    listingDate: '2020-09-24T15:17:38Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_COMP.svg',
    name: 'Compound',
    wallets: [
      {
        blockchain: 'Ethereum',
        blockchainName: 'Ethereum',
        currencyGroup: 'COMP',
        decimal_point: 18,
        explorer: 'https://etherscan.io/tx/',
        listingDate: '2020-09-24T15:17:38Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/ERC-20.svg',
        tokenSymbol: 'COMP',
        tokenType: 'ERC-20',
      },
    ],
    price: {
      day: '10.80',
      latestPrice: '1127099',
      month: '172.24',
      pair: 'comp/idr',
      week: '33.47',
      year: '36.22',
    },
  },
  // Chainlink
  {
    color: '#5664F5',
    currencyGroup: 'LINK',
    currencySymbol: 'LINK',
    decimal_point: 18,
    listingDate: '2020-09-24T15:17:39Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_LINK.svg',
    name: 'Chainlink',
    wallets: [
      {
        blockchain: 'Ethereum',
        blockchainName: 'Ethereum',
        currencyGroup: 'LINK',
        decimal_point: 18,
        explorer: 'https://etherscan.io/tx/',
        listingDate: '2020-09-24T15:17:39Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/ERC-20.svg',
        tokenSymbol: 'LINK',
        tokenType: 'ERC-20',
      },
    ],
    price: {
      day: '-1.46',
      latestPrice: '104512',
      month: '29.73',
      pair: 'link/idr',
      week: '11.39',
      year: '10.92',
    },
  },
  // Synthetix
  {
    color: '#0CD0FE',
    currencyGroup: 'SNX',
    currencySymbol: 'SNX',
    decimal_point: 18,
    listingDate: '2020-09-24T15:17:40Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_SNX.svg',
    name: 'Synthetix',
    wallets: [
      {
        blockchain: 'Ethereum',
        blockchainName: 'Ethereum',
        currencyGroup: 'SNX',
        decimal_point: 18,
        explorer: 'https://etherscan.io/tx/',
        listingDate: '2020-09-24T15:17:40Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/ERC-20.svg',
        tokenSymbol: 'SNX',
        tokenType: 'ERC-20',
      },
    ],
    price: {
      day: '13.77',
      latestPrice: '39911',
      month: '47.93',
      pair: 'snx/idr',
      week: '24.55',
      year: '-1.96',
    },
  },
  // Yearn.finance
  {
    color: '#006AE3',
    currencyGroup: 'YFI',
    currencySymbol: 'YFI',
    decimal_point: 18,
    listingDate: '2020-10-14T17:16:24Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_YFI.svg',
    name: 'Yearn.finance',
    wallets: [
      {
        blockchain: 'Ethereum',
        blockchainName: 'Ethereum',
        currencyGroup: 'YFI',
        decimal_point: 18,
        explorer: 'https://etherscan.io/tx/',
        listingDate: '2020-10-14T17:16:24Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/ERC-20.svg',
        tokenSymbol: 'YFI',
        tokenType: 'ERC-20',
      },
    ],
    price: {
      day: '-3.09',
      latestPrice: '105047147',
      month: '24.90',
      pair: 'yfi/idr',
      week: '-1.13',
      year: '16.45',
    },
  },
  // Uniswap
  {
    color: '#FF007A',
    currencyGroup: 'UNI',
    currencySymbol: 'UNI',
    decimal_point: 18,
    listingDate: '2020-10-14T17:16:55Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_UNI.svg',
    name: 'Uniswap',
    wallets: [
      {
        blockchain: 'Ethereum',
        blockchainName: 'Ethereum',
        currencyGroup: 'UNI',
        decimal_point: 18,
        explorer: 'https://etherscan.io/tx/',
        listingDate: '2020-10-14T17:16:55Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/ERC-20.svg',
        tokenSymbol: 'UNI',
        tokenType: 'ERC-20',
      },
    ],
    price: {
      day: '-0.57',
      latestPrice: '87685',
      month: '33.56',
      pair: 'uni/idr',
      week: '7.78',
      year: '-16.82',
    },
  },
  // Maker
  {
    color: '#52AC9F',
    currencyGroup: 'MKR',
    currencySymbol: 'MKR',
    decimal_point: 18,
    listingDate: '2020-10-14T23:57:22Z',
    logo: 'https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_MKR.svg',
    name: 'Maker',
    wallets: [
      {
        blockchain: 'Ethereum',
        blockchainName: 'Ethereum',
        currencyGroup: 'MKR',
        decimal_point: 18,
        explorer: 'https://etherscan.io/tx/',
        listingDate: '2020-10-14T23:57:22Z',
        logo: 'https://s3.ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/blockchain/ERC-20.svg',
        tokenSymbol: 'MKR',
        tokenType: 'ERC-20',
      },
    ],
    price: {
      day: '-3.60',
      latestPrice: '13227941',
      month: '36.10',
      pair: 'mkr/idr',
      week: '-7.76',
      year: '-1.13',
    },
  },
];
